### ISSUE TITLE
通过定义链接是怎么做到来定义内容的？

### ISSUE THREAD

**Issue by wayne0926** [YunYouJun/teachers-day#1]
本人小白，对对包涵🙏🏻
就是通过什么做到可以用?msg=这样的来设定显示的内容？
谢谢

**Comment by YunYouJun** [comment]
看这里。

https://github.com/YunYouJun/teachers-day/blob/1887922275f9bb5f3eaa5840ffd833b0a4711f8e/src/App.vue#L7-L18

**Comment by wayne0926** [comment]
> 看这里。
> 
> https://github.com/YunYouJun/teachers-day/blob/1887922275f9bb5f3eaa5840ffd833b0a4711f8e/src/App.vue#L7-L18

一定要用到VUE吗？

**Comment by YunYouJun** [comment]
……不用啊，这不就是原生 JS 么。

[mdn](https://developer.mozilla.org/zh-CN/) 搜一下 `new URL(document.location).searchParam`。

**Comment by wayne0926** [comment]
> ……不用啊，这不就是原生 JS 么。
> 
> [mdn](https://developer.mozilla.org/zh-CN/) 搜一下 `new URL(document.location).searchParam`。

```javascript
let params = (new URL(document.location)).searchParams;
let name = params.get('name'); // is the string "Jonathan Smith".
let age = parseInt(params.get('age')); // is the number 18
```
那这个MDN上的  https://developer.mozilla.org/zh-CN/docs/Web/API/URL/searchParams
这个例子是不是可以直接拿来用（赋值）呢？（let可以换为全局的var吗？）

**Comment by YunYouJun** [comment]
你试试就知道了。大部分情况下可以直接用 `let` 替代 `var`。你可以搜索一下区别。

**Comment by wayne0926** [comment]
> 你试试就知道了。大部分情况下可以直接用 `let` 替代 `var`。你可以搜索一下区别。

谢谢啦哈
